_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

random:
    path:     /random/{limit}
    defaults: { _controller: AcmeDemoBundle:Random:index }

cash:
    path:     /cash/{number}
    defaults: { _controller: AcmeDemoBundle:Cash:index }
order:
    path:     /order/{number}
    defaults: { _controller: AcmeDemoBundle:Order:index }

