parameters:
#    acme_cash.example.class: Acme\CashBundle\Example

services:
#    acme_cash.example:
#        class: %acme_cash.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
